[package]
name = "twelvedata"
version = "0.1.0"
description = "A Rust client for the Twelve Data API"
repository = "https://github.com/mazylol/twelvedata-rs"
readme = "README.md"
keywords = ["twelvedata", "api", "client", "rust"]
authors = ["Landon Porter <mazy@cock.li>"]
license = "MIT"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
